import { accountRequest } from "../core/student-auth.js";

const root=document.querySelector("#tvApp");
const mode=new URL(location.href).searchParams.get("mode")||"general";
let view=null;let timer=null;let phase="idle";let moveIndex=0;
const esc=(v)=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const student=(uid)=>view?.roster?.find((x)=>x.uid===uid)||null;
const label=(uid)=>{const s=student(uid);return s?`${Number(s.number)||"-"}번 ${s.name||"이름 없음"}`:"빈자리";};
const rot=(r)=>({0:"↑",90:"→",180:"↓",270:"←"})[Number(r)]||"↑";
function generalPos(){const out=new Map();(view.classroomLayout.general.seats||[]).forEach((uid,i)=>{if(uid)out.set(uid,{index:i,label:`일반 ${i+1}번 자리`,rotation:0});});return out;}
function targetPos(){const layout=view.classroomLayout;if(mode==="assessment"){const out=new Map();(layout.assessment.seats||[]).forEach((uid,i)=>{if(uid)out.set(uid,{index:i,label:`수행평가 ${i+1}번 자리`,rotation:0});});return out;}if(mode==="groups"){const out=new Map();const g=layout.groups;for(let group=1;group<=g.groupCount;group++){const members=g.members?.[group-1]||[];const desks=(g.desks||[]).filter((d)=>d.group===group).sort((a,b)=>a.index-b.index);members.forEach((uid,i)=>{const d=desks[i];if(uid&&d)out.set(uid,{index:d.index,label:`${group}모둠 · ${d.index+1}번 책상`,rotation:d.rotation});});}return out;}return generalPos();}
function movements(){const start=generalPos(),target=targetPos(),rows=[];for(const s of view.roster){const to=target.get(s.uid);if(!to)continue;const from=start.get(s.uid);rows.push({uid:s.uid,name:label(s.uid),from:from?.label||"현재 위치",to:to.label,rotation:to.rotation||0,moved:!from||from.index!==to.index||Number(to.rotation)!==0});}return rows.filter((x)=>x.moved);}
function progress(seconds){return `<div class="tv-progress"><i style="animation-duration:${seconds}s"></i></div>`;}
function idle(){clearTimeout(timer);phase="idle";const d=view.classroomLayout.display;root.innerHTML=`<section class="tv-idle"><div class="brand">PINCON · CLASSROOM DISPLAY</div><h1>${esc(d.message)}</h1><p>${view.classKey} · 곧 자리 이동 안내가 시작됩니다.</p>${progress(d.idleSeconds)}</section>`;timer=setTimeout(()=>{moveIndex=0;showMove();},d.idleSeconds*1000);}
function showMove(){clearTimeout(timer);const moves=movements();const d=view.classroomLayout.display;if(!moves.length){showFinal();return;}phase="move";const item=moves[moveIndex%moves.length];root.innerHTML=`<section class="tv-move"><header><div class="tv-kicker">자리 이동 ${moveIndex+1} / ${moves.length}</div><h2>${esc(item.name)}</h2></header><div class="move-stage"><div class="move-box"><span>현재</span><strong>${esc(item.from)}</strong></div><div class="move-arrow">→</div><div class="move-box"><span>이동</span><strong>${esc(item.to)}</strong>${mode==="groups"?`<em>${rot(item.rotation)}</em>`:""}</div></div><footer class="tv-step">${mode==="groups"?`책상 방향 ${rot(item.rotation)} · `:""}통로를 막지 않게 순서대로 이동하세요.</footer>${progress(d.stepSeconds)}</section>`;timer=setTimeout(()=>{moveIndex++;if(moveIndex>=moves.length)showFinal();else showMove();},d.stepSeconds*1000);}
function finalCells(){const l=view.classroomLayout;if(mode==="groups"){const g=l.groups,map=targetPos(),byIndex=new Map();for(const [uid,p] of map)byIndex.set(p.index,uid);const deskMap=new Map((g.desks||[]).map((d)=>[d.index,d]));const total=g.deskRows*g.deskCols;return{cols:g.deskCols,cells:Array.from({length:total},(_,i)=>{const d=deskMap.get(i),uid=byIndex.get(i)||"";return d?`<div class="tv-seat ${uid?"":"empty"}"><span class="grp">${d.group}모둠</span><span class="rot">${rot(d.rotation)}</span><small>${i+1}번 책상</small><strong>${esc(label(uid))}</strong></div>`:`<div class="tv-seat empty"></div>`;})};}if(mode==="assessment"){const a=l.assessment,cols=a.lines,rows=Math.ceil(Math.max(view.roster.length,a.seats?.length||0)/cols);return{cols,cells:Array.from({length:rows*cols},(_,i)=>{const uid=a.seats?.[i]||"";return`<div class="tv-seat ${uid?"":"empty"}"><small>${i+1}번 자리</small><strong>${esc(label(uid))}</strong></div>`;})};}const g=l.general;return{cols:g.cols,cells:Array.from({length:g.rows*g.cols},(_,i)=>{const uid=g.seats?.[i]||"";return`<div class="tv-seat ${uid?"":"empty"}"><small>${i+1}번 자리</small><strong>${esc(label(uid))}</strong></div>`;})};}
function showFinal(){clearTimeout(timer);phase="final";const d=view.classroomLayout.display;const data=finalCells();const title=mode==="groups"?"모둠 배치 완료":mode==="assessment"?`${view.classroomLayout.assessment.lines}줄 수행평가 배치`:"일반 자리배치";root.innerHTML=`<section class="tv-final"><h1>${title}</h1><p>최종 위치를 확인한 뒤 조용히 착석해주세요.</p><div class="tv-teacher">교탁</div><div class="tv-room" style="grid-template-columns:repeat(${data.cols},1fr)">${data.cells.join("")}</div>${progress(8)}</section>`;timer=setTimeout(idle,8000);}
async function refresh(){try{view=await accountRequest("/api/class-ops/classroom-layout");if(!phase||phase==="idle")idle();}catch{root.innerHTML=`<section class="tv-error"><strong>교실 배치를 불러오지 못했습니다</strong><span>로그인과 권한을 확인해주세요.</span></section>`;}}
refresh();setInterval(async()=>{try{const next=await accountRequest("/api/class-ops/classroom-layout");if(next.updatedAtMs!==view?.updatedAtMs)view=next;}catch{}},30000);
